### ISSUE TITLE
⚙ Support for popular libraries

### ISSUE THREAD

**Issue by MatiDragon-YT** [cleolibrary/CLEO-Redux#18]
- IniFiles
- IntOperations
- FileSystemOperations
- [CLEO ImGui](https://github.com/user-grinch/CLEOImGui)
- [CLEO Plus](https://github.com/JuniorDjjr/CLEOPlus)

**Comment by x87** [comment]
If the question is in relation to SA: DE, then it's not possible since those plugins are

1) 32-bit and the game is 64-bit
2) they use CLEO SDK which uses interfaces not compatible with SA: DE (all offsets are different)
3) they use hardcoded opcode number conflicting with SA: DE original opcodes

Eventually we will get an SDK for developing custom commands for any game and the maintainers of those plugins could rewrite them if they want.
