### ISSUE TITLE
[Redux SA:DE] - Using Text class has some bugs!

### ISSUE THREAD

**Issue by nonunknown** [cleolibrary/CLEO-Redux#19]
PS: Using javascript

First bug is, every time you call any method from the class Text which creates a text on screen the word `missing!` appears in front of it:

![image](https://user-images.githubusercontent.com/58845030/144767938-5574d947-33b5-4c33-9ca0-eb297f0926d0.png)

Secong bug is, if your string is too big, the game closes without any crash message:
```js

//Key 117 is F6
var player = new Player(0);
var playerHasControl = player.isControlOn();
var isMenuActive = false;
var CM = {
    showText: function (msg) {
        Text.Print(msg, 500, 0);
    }
};
while (true) {
    if (Pad.IsKeyPressed(117)) {
        if (!isMenuActive) {
            isMenuActive = true;
            CM.showText("hi\0");
            player.setControl(false);
            var i = 0;
            var msg = "";
            while (i < 10) {
                msg += String(i) + " ";
                i++;
                CM.showText(msg);
                wait(500);
            }
        }
        else {
            isMenuActive = false;
            player.setControl(true);
        }
        log("player is being controlled: " + String(player.isControlOn()));
    }
    wait(100);
}
```

Third bug: Using `Text.Display()` has no method to clear it() like Help and Print

I took some reading about menus in CLEO and seems you need to create GXT in order to show strings in-game, and to solve that maybe a GXT class should exists? like `Text.Print(GXT("any string here"),500,0)`

**Comment by XMDS** [comment]
1. Use text commands to display "missing" at the end of the string:

All built-in commands of the game cannot directly output strings.  It uses the call text to display the string, the parameter of the command is actually the "Key Name" of the string:
```
03E5  Text.PrintHelp(key: gxt_key)

Key  string
CLEO1  Hello GTA

Text.PrintHelp('CLEO1')
```
It will display "hello GTA" correctly


If you are a player of the classic GTA trilogy, you should know how to use fxt files to customize text in CLEO.  Unfortunately, currently CLEO Redux does not support custom text, so it has this problem.  It may take a long time to support.


2.The length of "key name" is too long, causing the game to crash and report an error?

Same as above.  "key name" is a short string.  It certainly has a length limit.Because it only serves as a name


3.Turn off the subtitles displayed by the DISPLAY_TEXT command?

```
03F0 USE_TEXT_COMMANDS

Text.UseCommands(state: bool)

1=enable 0=Disable
```
There are many types of TEXT commands in the game, and they have independent close commands.  All text commands with coordinates are closed with 03F0.  In addition, when calling the texture command, you need to turn on

**Comment by GouLiGuoJiaNaive** [comment]
I have a similar problem, SA:DE supports Chinese, but I don’t know what encoding it is, so every time I try to use them, I always get garbled characters.

**Comment by XMDS** [comment]
> I have a similar problem, SA:DE supports Chinese, but I don’t know what encoding it is, so every time I try to use them, I always get garbled characters.

In fact, you cannot use Chinese.  Because the name of the current Text command output is "key name", the game only uses English "key name".  There is currently no command to directly display custom strings.

**Comment by x87** [comment]
CLEO 0.8.5 supports FXT for custom text content
https://github.com/cleolibrary/CLEO-Redux/blob/master/using-fxt.md
